export enum TagTypes {
  SPECILITY = "specilities",
  DOCTORS = "doctor",
  PATIENTS = "Patients",
  ADMIN = "admin",
  SUPER_ADMIN = "super-admin",
  SCHEDULE = "schedule",
  USER = "user",
  DOCTOR_SCHEDULE = "doctor-schedule",
  AUTH = "auth",
  APPOINTMENT = "appointment",
  METADTA = "metaData",
  PRESCRIPTION = "prescription",
  REVIEW = "review",
}

export const tagTypesValues = [
  TagTypes.SPECILITY,
  TagTypes.ADMIN,
  TagTypes.DOCTORS,
  TagTypes.PATIENTS,
  TagTypes.SUPER_ADMIN,
  TagTypes.SCHEDULE,
  TagTypes.USER,
  TagTypes.DOCTOR_SCHEDULE,
  TagTypes.AUTH,
  TagTypes.APPOINTMENT,
  TagTypes.METADTA,
  TagTypes.PRESCRIPTION,
  TagTypes.REVIEW,
];
