const assets = {
  images: {
    logo: require("./image/Logo.png"),
    footerLogo: require("./image/footer-logo.png"),
    yellow: require("./image/calendar.png"),
    doctorBanner: require("./image/doctor-banner.png"),
    dotGroup: require("./image/dot-group.png"),
    greenFrame: require("./image/green-frame.png"),
    labTest: require("./image/lab-test.png"),
    medicine: require("./image/medicine.png"),
    redFrame: require("./image/red-frame.png"),
    statistiscope: require("./image/staticscope.png"),
    yellowFrame: require("./image/yrllow-frame.png"),
    doctor2: require("./image/doctor-2.png"),
    stataticScope2: require("./image/statiticScope2.png"),
    doctor4: require("./image/doctor4.png"),
    doctor5: require("./image/doctor5.png"),
    doctor6: require("./image/doctor6.png"),
    stetoscope2: require("./image/Stetoscope.png"),
    familyOnBeach: require("./image/familyOnBeach.png"),
    howItWork: require("./image/how-it-works-img.png"),
  },
  svg: {
    arrow: require("./svgs/arrow.svg"),
    cardiology: require("./svgs/Cardiology.svg"),
    dentist: require("./svgs/Dentist.svg"),
    neurology: require("./svgs/Neurology.svg"),
    opthalmology: require("./svgs/Ophthalmology.svg"),
    urology: require("./svgs/Urology.svg"),
    awardIcon: require("./svgs/award-icon.svg"),
    brain: require("./svgs/brain.svg"),
    calendar: require("./svgs/calender.svg"),
    dna: require("./svgs/dna.svg"),
    doctorSearch: require("./svgs/doctorSearch.svg"),
    grid: require("./svgs/grid.svg"),
    kidney: require("./svgs/kidney.svg"),
    location: require("./svgs/location.svg"),
    profile: require("./svgs/profile.svg"),
    schedule: require("./svgs/schedule.svg"),
    search: require("./svgs/search.svg"),
    solution: require("./svgs/solution.svg"),
  },
};

export default assets;
